# Exercise - INCOMPLETE Compose YAML
# Adding Orderer #4 and #5 in the RAFT cluster
# TLS parmeters are already setup for the orderer instance
# Look for "<<< SETUP the appropriate properties Here >>>" and setp the properties

version: '2'

networks:
  airline:

# Storage for additional orderer containers
volumes:
  data-orderer4.acme.com:
  data-orderer5.acme.com:


services:

  
  # Orderer4 service
  orderer4.acme.com:
    container_name: orderer4.acme.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    command: orderer
    # Override environment variables for orderer in this section
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=INFO
      # TLS Setup
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/tls/ca.crt]

      # RAFT related setup
      # <<< SETUP the appropriate properties Here >>>

    # Host folder mappings
    volumes:
    # Folder with genesis block
    - ${PWD}/config/orderer:/var/hyperledger/config
    # Map the folder with MSP for orderer
    - ${PWD}/config/crypto-config/ordererOrganizations/acme.com/orderers/orderer4.acme.com/msp:/var/hyperledger/msp
    # Added to support the TLS setup
    - ${PWD}/config/crypto-config/ordererOrganizations/acme.com/orderers/orderer4.acme.com/tls:/var/hyperledger/tls
    - data-orderer4.acme.com:/var/ledger
    networks:
      - airline

  # Orderer5 service
  orderer5.acme.com:
    container_name: orderer5.acme.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    command: orderer
    # Override environment variables for orderer in this section
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=INFO
      # TLS Setup
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/tls/ca.crt]
      
      # RAFT related setup
      # <<< SETUP the appropriate properties Here >>>

    # Host folder mappings
    volumes:
    # Folder with genesis block
    - ${PWD}/config/orderer:/var/hyperledger/config
    # Map the folder with MSP for orderer
    - ${PWD}/config/crypto-config/ordererOrganizations/acme.com/orderers/orderer5.acme.com/msp:/var/hyperledger/msp
    # Added to support the TLS setup
    - ${PWD}/config/crypto-config/ordererOrganizations/acme.com/orderers/orderer5.acme.com/tls:/var/hyperledger/tls
    - data-orderer5.acme.com:/var/ledger
    networks:
      - airline