# Compose file for launching the test setup with
# a Peer for Acme and a Peer for Budget

version: '2'

networks:
  airline:

services:

  # Orderer service
  orderer.acme.com:
    environment:
      # Add the environment properties to ENABLE TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/tls/ca.crt]

  # Enable the TLS for Acme peer1
  peer1.acme.com:
    environment:
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt

  # Enable the TLS for Budget peer1
  peer1.budget.com:
    environment:
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
